name: Abaddon CI

on: [ push, pull_request ]

jobs:
  linux:
    name: Linux (x86_64)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check --verbose

      - name: Build release binary
        run: cargo build --release --verbose

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: abaddon-linux-x86_64
          path: target/release/abaddon

  macos:
    name: macOS (x86_64)
    runs-on: macos-15-intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check --target x86_64-apple-darwin --verbose

      - name: Build release binary (macosx64)
        run: cargo build --release --target x86_64-apple-darwin --verbose

      - name: Upload macOS x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: abaddon-macos-x86_64
          path: target/x86_64-apple-darwin/release/abaddon
